Занятие 2. Базовый css
Timur233/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-26 06:59 UTC by Timur233

- Верстка модального окна
- Функционал radio-buttons
- Стили модального окна

2021-09-26 19:25 UTC, BekStar7 commented
<img width="1108" alt="Снимок экрана 2021-09-26 в 23 23 02" src="https://user-images.githubusercontent.com/29562716/134821430-bc98d72d-1286-4bba-8f4d-8c1e69eefdc9.png">

2021-09-26 19:34 UTC, BekStar7 requested changes

2021-09-26 19:34 UTC, BekStar7 commented on index.html
> +                    <h3 class="product-title">Футболка "Эволюционируй или сдохни"</h3>
Можно было использовать h2

2021-09-26 19:34 UTC, BekStar7 commented on index.html
> +
лишняя строка

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap');
Загружать все шрифты и их парметры не нужно, достаточно 400, 600
Всегда нужно загружать, то что используется, чтобы браузер при первом загрузке меньше качал

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +    overflow-y: scroll;
не обязательно нужен он

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +    padding: 25px 25px;
Лишний код

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +    margin: 0 -4px;
использовать `-` плохая практика, его надо использовать в крайнем случае, специфичных кейсах

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +    min-width: 134px;
можно меньше задать или чисто за счет padding делать размер 
Вдруг текст надо менять =)

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +    font-family: 'Open Sans', sans-serif;
FYI, Font-family наследуется от body, но т.к. нету reset.css, оставь
Просто для развитие

2021-09-26 19:34 UTC, BekStar7 commented on src/css/style.css
> +    margin: 0 -4px 24px -4px;
писал ранее

2021-09-27 01:58 UTC, Timur233 commented on src/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap');
Сорри, загрузил все так как не знаю за ранее сколько начертаний будет в проекте))

2021-09-27 01:58 UTC, Timur233 commented on src/css/style.css
> +    margin: 0 -4px;
Понял!

2021-09-27 05:38 UTC, BekStar7 commented on src/css/style.css
> +    margin: 0 -4px;
По мере появление добавляй

2021-09-27 09:08 UTC, BekStar7 approved these changes

2021-09-27 09:39 UTC, merged